# Generated by Django 6.0.7 on 2026-07-27 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=64)),
                ('programme_name', models.CharField(max_length=255)),
                ('year_completed', models.IntegerField()),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cleared_department', models.BooleanField(default=False)),
                ('cleared_accounts', models.BooleanField(default=False)),
                ('cleared_library', models.BooleanField(default=False)),
                ('zone', models.CharField(choices=[('harare', 'Harare'), ('outside_harare', 'Outside Harare')], max_length=20)),
                ('harare_address', models.TextField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('cash_deposit', 'Cash deposit')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_transit', 'In transit'), ('collected', 'Collected'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zimpost_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='branches.zimpostbranch')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='idx_requests_status'), models.Index(fields=['-created_at'], name='idx_requests_created'), models.Index(fields=['zone'], name='idx_requests_zone')],
            },
        ),
    ]
