# Generated by Django 6.0.7 on 2026-10-01 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


STATUS_MAP = {"submitted": "received", "in_transit": "dispatched"}


def forwards(apps, schema_editor):
    Request = apps.get_model("requests_app", "Request")
    RequestEvent = apps.get_model("requests_app", "RequestEvent")

    for old, new in STATUS_MAP.items():
        Request.objects.filter(status=old).update(status=new)
    # B1.5: stale rejection reasons go; rejected rows without one get a placeholder
    # so the new CHECK constraint can be applied.
    Request.objects.exclude(status="rejected").update(status_reason=None)
    Request.objects.filter(status="rejected", status_reason__isnull=True).update(
        status_reason="No reason recorded"
    )
    Request.objects.filter(status="rejected", status_reason="").update(
        status_reason="No reason recorded"
    )

    # B2.2: backfill history. created_at is auto_now_add, so switch that off
    # for the duration to keep the original timestamps.
    created_field = RequestEvent._meta.get_field("created_at")
    created_field.auto_now_add = False
    try:
        events = []
        for r in Request.objects.all().iterator():
            events.append(
                RequestEvent(
                    request=r,
                    event_type="status_change",
                    field="status",
                    from_value="",
                    to_value="received",
                    note="Request received",
                    created_at=r.created_at,
                )
            )
            if r.status != "received":
                events.append(
                    RequestEvent(
                        request=r,
                        event_type="status_change",
                        field="status",
                        from_value="received",
                        to_value=r.status,
                        note="Migrated from the previous status flow",
                        created_at=r.updated_at,
                    )
                )
        RequestEvent.objects.bulk_create(events, batch_size=500)
    finally:
        created_field.auto_now_add = True


def backwards(apps, schema_editor):
    Request = apps.get_model("requests_app", "Request")
    Request.objects.filter(status="received").update(status="submitted")
    Request.objects.filter(status="dispatched").update(status="in_transit")
    Request.objects.filter(status__in=["submitted_to_msu", "collected_from_msu"]).update(
        status="submitted"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20)),
                ('bike_registration', models.CharField(blank=True, max_length=32)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_change', 'Status change'), ('details_edit', 'Details edit'), ('dispatch', 'Dispatch'), ('payment', 'Payment'), ('note', 'Note')], max_length=20)),
                ('field', models.CharField(blank=True, max_length=40)),
                ('from_value', models.TextField(blank=True, null=True)),
                ('to_value', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='request',
            name='zimpost_tracking_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='request',
            name='reg_number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('submitted_to_msu', 'Submitted to MSU'), ('collected_from_msu', 'Collected from MSU'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('collected', 'Collected')], default='received', max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('out_for_delivery', 'Out for delivery'), ('closed', 'Closed')], default='out_for_delivery', max_length=20)),
                ('dispatched_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests_app.dispatchbatch'),
        ),
        migrations.AddField(
            model_name='dispatchbatch',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='requests_app.driver'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requests_app.request'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['request', '-created_at'], name='idx_events_request'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
