#!/usr/bin/env bash
#
# Build and (re)start the application. Run for the first deploy and for every
# update afterwards.
#
#   sudo bash /srv/msu/deploy/deploy.sh
#
# What it does:
#   1. installs/updates Python and Node dependencies
#   2. runs database migrations
#   3. collects Django admin static files
#   4. builds the frontend for Node (npm run build:server)
#   5. restarts both systemd services and verifies they answer
#
# Assumes setup-server.sh has already run and both .env files exist.

set -euo pipefail

APP_USER="msu"
APP_DIR="/srv/msu"
BACKEND="$APP_DIR/Backend"
FRONTEND="$APP_DIR/Frontend"
PYTHON="python3.12"

# Public hostname, used only by the final nginx health check. It must be a name
# nginx serves: after certbot, requests carrying any other Host (127.0.0.1
# included) hit certbot's redirect block and get a 404.
SITE_DOMAIN="${SITE_DOMAIN:-collectmytranscriptmsu.com}"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31m[error]\033[0m %s\n' "$1" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run this with sudo."
[[ -d "$BACKEND"  ]] || die "$BACKEND not found. Copy the code to $APP_DIR first."
[[ -f "$BACKEND/.env"  ]] || die "$BACKEND/.env is missing (see deploy/env-templates/)."
[[ -f "$FRONTEND/.env" ]] || die "$FRONTEND/.env is missing (see deploy/env-templates/)."

# Everything that touches the app runs as the unprivileged service user so no
# root-owned files end up in the tree.
#
# HOME must be set explicitly: sudo does not point it at the target user by
# default, and npm would then try to write its cache to /root/.npm and fail.
APP_HOME="$(getent passwd "$APP_USER" | cut -d: -f6)"
as_app() { sudo -u "$APP_USER" env "HOME=$APP_HOME" "PATH=$PATH" "$@"; }

log "Fixing ownership"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# ------------------------------------------------------------------- backend

log "Installing Python dependencies"
if [[ ! -d "$BACKEND/venv" ]]; then
    as_app "$PYTHON" -m venv "$BACKEND/venv"
fi
as_app "$BACKEND/venv/bin/pip" install --quiet --upgrade pip
as_app "$BACKEND/venv/bin/pip" install --quiet -r "$BACKEND/requirements.txt"

log "Checking Django configuration"
# Catches a missing SECRET_KEY, bad ALLOWED_HOSTS, or an unreachable database
# before anything is restarted.
( cd "$BACKEND" && as_app "$BACKEND/venv/bin/python" manage.py check --deploy ) || \
    die "Django checks failed — fix Backend/.env before continuing."

log "Running database migrations"
( cd "$BACKEND" && as_app "$BACKEND/venv/bin/python" manage.py migrate --noinput )

log "Collecting Django admin static files"
( cd "$BACKEND" && as_app "$BACKEND/venv/bin/python" manage.py collectstatic --noinput --clear )

# ------------------------------------------------------------------ frontend

log "Checking Node version"
NODE_MAJOR="$(node --version 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/' || echo 0)"
if (( NODE_MAJOR < 22 )); then
    die "Node $(node --version 2>/dev/null || echo 'not installed') is too old.
     The frontend requires Node >= 22.12. Re-run setup-server.sh, which installs Node 24."
fi

log "Installing Node dependencies"
# `npm ci` installs exactly what package-lock.json pins — reproducible, and the
# right default. devDependencies are needed (vite, nitro and the Tailwind plugin
# do the build), so this is a full install rather than --omit=dev.
#
# It can still fail if the lockfile was written by a different npm major than
# the one installed here, which changes how the tree resolves. Rather than block
# the deploy, fall back to `npm install` and say so loudly: the build is
# verified by the smoke checks at the end either way.
if ! ( cd "$FRONTEND" && as_app npm ci --no-audit --no-fund ); then
    warn "npm ci failed — falling back to 'npm install'."
    warn "This usually means package-lock.json was generated by a different npm"
    warn "major version. Commit the regenerated lockfile to make builds reproducible."
    ( cd "$FRONTEND" && as_app npm install --no-audit --no-fund )
fi

log "Building the frontend (this is the memory-hungry step)"
# build:server sets BUILD_NODE_SERVER=1, which selects the nitro node-server
# preset and emits a self-listening server at .output/server/index.mjs. A plain
# `npm run build` produces a fetch handler that systemd cannot run.
( cd "$FRONTEND" && as_app npm run build:server )

[[ -f "$FRONTEND/.output/server/index.mjs" ]] || \
    die "Build did not produce .output/server/index.mjs"

# --------------------------------------------------------------- services

log "Installing systemd units"
install -m 644 "$APP_DIR/deploy/systemd/msu-backend.service"  /etc/systemd/system/
install -m 644 "$APP_DIR/deploy/systemd/msu-frontend.service" /etc/systemd/system/
systemctl daemon-reload

log "Restarting services"
systemctl enable msu-backend msu-frontend >/dev/null 2>&1 || true
systemctl restart msu-backend
systemctl restart msu-frontend

# ------------------------------------------------------------------- verify

log "Verifying"
sleep 4

# check <label> <expected-status> <curl args...>
# Trailing curl arguments rather than a single URL, so callers can pass --resolve
# or -H without the quoting being flattened into one argument.
check() {
    local name="$1" expected="$2"
    shift 2
    local code
    # No -f here, deliberately: --fail makes curl exit non-zero on 4xx, which
    # would fire the `|| echo 000` fallback and concatenate onto the real code
    # (producing "401000"). Without it, curl exits 0 for any HTTP response and
    # the fallback only fires when the connection itself fails.
    code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 10 "$@" 2>/dev/null || echo 000)"
    if [[ "$code" == "$expected" ]]; then
        printf '    \033[1;32mok\033[0m   %-28s %s\n' "$name" "$code"
    else
        printf '    \033[1;31mFAIL\033[0m %-28s got %s, expected %s\n' "$name" "$code" "$expected"
        return 1
    fi
}

failed=0
check "backend (gunicorn)"  200 "http://127.0.0.1:8000/api/branches/?active=true" || failed=1
check "backend admin-gated" 401 "http://127.0.0.1:8000/api/requests/"             || failed=1
check "frontend (node ssr)" 200 "http://127.0.0.1:3000/"                          || failed=1

# Check nginx the way a real visitor reaches it: with the site's own Host name.
#
# Requesting http://127.0.0.1/ does NOT work once certbot has run. Certbot's
# generated port-80 block redirects only the hostnames it was issued for and
# ends with `return 404; # managed by Certbot`, so any other Host — 127.0.0.1
# included — gets a 404 that says nothing about application health.
#
# Once TLS is present, --resolve pins the domain to loopback so the request
# stays on this machine while still carrying the right SNI and Host. Before TLS
# exists, fall back to port 80 with an explicit Host header.
if systemctl is-active --quiet nginx; then
    if curl -sSk --resolve "$SITE_DOMAIN:443:127.0.0.1" -o /dev/null \
            --max-time 10 "https://$SITE_DOMAIN/" 2>/dev/null; then
        # -k keeps this a routing check: certificate validity is a separate
        # concern and shouldn't make a healthy deploy look broken.
        check "through nginx (https)" 200 \
            -k --resolve "$SITE_DOMAIN:443:127.0.0.1" "https://$SITE_DOMAIN/" || failed=1
    else
        check "through nginx (http)" 200 \
            -H "Host: $SITE_DOMAIN" "http://127.0.0.1/" || failed=1
    fi
else
    printf '    \033[1;33mskip\033[0m through nginx (nginx not running yet)\n'
fi

if (( failed )); then
    cat <<'EOF'

Something is not answering. Check the logs:
    sudo journalctl -u msu-backend  -n 50 --no-pager
    sudo journalctl -u msu-frontend -n 50 --no-pager
    sudo tail -n 50 /var/log/nginx/msu-error.log
EOF
    exit 1
fi

log "$(printf '\033[1;32mDeploy complete\033[0m')"
systemctl --no-pager --lines=0 status msu-backend msu-frontend | grep -E 'msu-|Active:'
